apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: sm-kafka-data
  namespace: kafka-s3
spec:
  details:
    dataFormat: json
    connection:
      name: kafka
      kafka:
        kafka_topic_name: sm
        kafka_bootstrap_servers: "kafka.fybrik-system:9092"
        namespace: fybrik-system
  secretRef:
      name: s3-credentials
  metadata:
    name:  s3-store
    geography: UK
    tags:
      sm: true
    columns:
      - name: id
        tags:
          PII: true
          blocked: true
